CREATE TABLE ACTION_LOG(
  LOGID NUMBER(24,0) PRIMARY KEY NOT NULL,
  CHUONGTRINHID NUMBER(24,0) NOT NULL REFERENCES DM_CHUONG_TRINH(CHUONGTRINHID),
  TABLE_LOG varchar(50) NOT NULL,
  COLUMN_ID_LOG_NAME VARCHAR(100) NOT NULL,
  USERID NUMBER(24,0) NOT NULL REFERENCES VMS_USER(USERID),
  CREATEDTIME TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR2(200)
)tablespace "USERS";

CREATE SEQUENCE ACTION_LOG_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;