ALTER TABLE MOBI_DATA_ORDER_DATA_CODE ADD CONSTRAINT "ORDER_DATA_SERIAL_UQ" UNIQUE(Serial);

CREATE TABLE MOBI_DATA_USEDCARDCODE
(
  UsedCardCodeID        NUMBER(24,0)        PRIMARY KEY NOT NULL ,
  CardCode              VARCHAR(36),
  CONSTRAINT "USEDCARDCODE_CARDCODE_UQ" UNIQUE(CardCode)
) TABLESPACE "USERS";

CREATE SEQUENCE  MOBI_DATA_CARDCODE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
commit;