SET DEFINE OFF;
CREATE USER DGNVKHDN_OWNER IDENTIFIED BY 123456 DEFAULT TABLESPACE DGNVKHDN_DATA TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SYNONYM TO DGNVKHDN_OWNER;
connect DGNVKHDN_OWNER/123456;

commit;