CREATE TABLE VMS_USERGROUP
(
   UserGroupID            NUMBER(24,0)                        NOT NULL PRIMARY KEY,
   Code                   VARCHAR2(50 CHAR)                   NOT NULL,
   Name                   VARCHAR2(250 CHAR)                  NOT NULL,
   Description            VARCHAR2(250 CHAR)                   	NULL,
   CreatedDate            TIMESTAMP                      NOT NULL,
   ModifiedDate           TIMESTAMP                      NULL,
  CONSTRAINT "VMS_USERGROUP_UQ" UNIQUE (Code)
) TABLESPACE "USERS";

CREATE TABLE VMS_ROLE
(
   RoleID                 NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   Role                   VARCHAR2(50 CHAR)                   NOT NULL,
   Name                   VARCHAR2(250 CHAR)                  NOT NULL,
   Description            VARCHAR2(250 CHAR)                   NULL,
   CreatedDate            TIMESTAMP                      NOT NULL,
   ModifiedDate           TIMESTAMP                      NULL,
  CONSTRAINT "VMS_ROLE_UQ" UNIQUE (Role)
) TABLESPACE "USERS";

CREATE TABLE VMS_DEPARTMENT
(
   DepartmentID                 NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   Code                   VARCHAR2(50 CHAR)                   NOT NULL,
   Name                   VARCHAR2(250 CHAR)                  NOT NULL,
   Address                VARCHAR2(500 CHAR)     NULL,
   Tel                    VARCHAR(250 CHAR) NULL,
   ContactName            VARCHAR2(250 CHAR) NULL,
   DepartmentType            VARCHAR(20)                  NOT NULL, -- CN: Chi nhanh, SHOP: Cua hang, DAILY: Dai ly,
   CreatedDate            TIMESTAMP                      NOT NULL,
   ModifiedDate           TIMESTAMP                      NULL,
  CONSTRAINT "VMS_DEPARTMENT_CODE_UQ" UNIQUE (Code)
) TABLESPACE "USERS";

CREATE TABLE VMS_USER
(
   UserID                 NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   Username               VARCHAR2(250 CHAR)                  NOT NULL,
   Password               VARCHAR2(250 CHAR)                  NULL,
   LastTemporaryPass               VARCHAR2(250 CHAR)                  NULL,
   LastExpiredTime        TIMESTAMP,
   Email                  VARCHAR2(250 CHAR)                  NULL,
   DisplayName              VARCHAR2(250 CHAR)                  NOT NULL,
   MobileNumber           VARCHAR2(20 CHAR)                   NULL,
   Status                 NUMBER(24,0)                            NULL,
   DepartmentID           NUMBER(24,0)                            NULL,
   UserGroupID            NUMBER(24,0)                            NOT NULL,
   CreatedDate            TIMESTAMP                      NOT NULL,
   ModifiedDate           TIMESTAMP                      NULL,

   CONSTRAINT "VMS_USER_USERNAME_UQ" UNIQUE (Username),
   CONSTRAINT "VMS_USER_EMAIL_UQ" UNIQUE (Email),
   CONSTRAINT "VMS_USER_MOBILE_UQ" UNIQUE (MobileNumber),
   CONSTRAINT "VMS_USER_DEPT_FK" FOREIGN KEY(DepartmentID) REFERENCES VMS_DEPARTMENT(DepartmentID),

   CONSTRAINT "VMS_USER_USERGROUP_FK" FOREIGN KEY(UserGroupID) REFERENCES VMS_USERGROUP(UserGroupID)
) TABLESPACE "USERS";

CREATE TABLE VMS_USER_PASSWORD (
   UserPasswordID                 NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   Password               VARCHAR2(250 CHAR)                  NOT NULL,
   CreatedTime            TIMESTAMP                      NOT NULL,
   ExpiredTime            TIMESTAMP                      NOT NULL,
   Status                 INTEGER NOT NULL,
   UserID                 NUMBER(24, 0) NOT NULL,
   CONSTRAINT "VMS_USERPASS_USER_FK" FOREIGN KEY(UserID) REFERENCES VMS_USER(UserID)

) TABLESPACE "USERS";

CREATE TABLE VMS_USERGROUP_ROLE (
   UserGroupRoleID             NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   UserGroupID                 NUMBER(24,0)                            NOT NULL,
   RoleID                 NUMBER(24,0)                            NOT NULL,
   CONSTRAINT "VMS_USERGROUPROLE_UQ" UNIQUE (UserGroupID, RoleID),
   CONSTRAINT "VMS_USERGROUPROLE_USER_FK" FOREIGN KEY(UserGroupID) REFERENCES VMS_USERGROUP(UserGroupID),
   CONSTRAINT "VMS_USERGROUPROLE_ROLE_FK" FOREIGN KEY(RoleID) REFERENCES VMS_ROLE(RoleID)
) TABLESPACE "USERS";

CREATE TABLE VMS_USER_ROLE (
   UserRoleID             NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   UserID                 NUMBER(24,0)                            NOT NULL,
   RoleID                 NUMBER(24,0)                            NOT NULL,
   CONSTRAINT "VMS_USER_ROLE_UQ" UNIQUE (UserID, RoleID),
   CONSTRAINT "VMS_USER_ROLE_USER_FK" FOREIGN KEY(UserID) REFERENCES VMS_USER(UserID),
   CONSTRAINT "VMS_USER_ROLE_ROLE_FK" FOREIGN KEY(RoleID) REFERENCES VMS_ROLE(RoleID)
) TABLESPACE "USERS";

CREATE TABLE VMS_GIFT
(
   GiftID                 NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   Code                   VARCHAR2(50 CHAR)                   NOT NULL,
   Name                   VARCHAR2(250 CHAR)                  NOT NULL,
   CreatedDate            TIMESTAMP                      NOT NULL,
   ModifiedDate           TIMESTAMP                      NULL,
  CONSTRAINT "VMS_GIFT_UQ" UNIQUE (Code)
) TABLESPACE "USERS";

CREATE TABLE VMS_GIFT_AGENT_TRANSACTION
(
   GiftTransactionID                 NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   AgentID                   NUMBER(24,0)                   NOT NULL,
   GiftID                   NUMBER(24,0)                   NOT NULL,
   Quantity                   NUMBER(24,0)                   NOT NULL,
   TransactionDate        TIMESTAMP         NOT NULL,
   Name                   VARCHAR(255)      NOT NULL,
   Notes                  CLOB              NULL,
   Remaining              NUMBER(24, 0)     DEFAULT 0 NOT NULL,
   Transporter            VARCHAR(255) NOT NULL,
   ConfirmedUserID        NUMBER(24, 0),
   Status                 INTEGER NOT NULL,
   CreatedDate            TIMESTAMP                      NOT NULL,
   ModifiedDate           TIMESTAMP                      NULL,
   ConfirmedDate           TIMESTAMP                      NULL,
   CONSTRAINT "VMS_GIFT_AGENT_AGENT_FK" FOREIGN KEY(AgentID) REFERENCES VMS_DEPARTMENT(DepartmentID),
   CONSTRAINT "VMS_GIFT_AGENT_GIFT_FK" FOREIGN KEY(GiftID) REFERENCES VMS_GIFT(GiftID)
) TABLESPACE "USERS";

CREATE TABLE DM_CHUONG_TRINH(
  CHUONGTRINHID NUMBER(24,0) NOT NULL PRIMARY KEY,
  CODE VARCHAR(100 CHAR) NOT NULL,
  DESCRIPTION VARCHAR(250 CHAR) NOT NULL,
  CREATEDDATE TIMESTAMP NOT NULL,
  MODIFIEDDATE TIMESTAMP,
  CONSTRAINT "UQ_CHUONGTRINH_CODE" UNIQUE(CODE)
)TABLESPACE "USERS";

CREATE TABLE VMS_CHINHANH(
  CHINHANHID NUMBER(24, 0) NOT NULL PRIMARY KEY,
  CHINHANH INTEGER NOT NULL,
  NAME VARCHAR2(300 CHAR) NOT NULL,
  CONSTRAINT "VMS_CHINHANH_CN_UQ" UNIQUE(CHINHANH)
)TABLESPACE "USERS";

CREATE TABLE BRANCH_MAPPING(
  BRANCHMAPPINGID NUMBER(24,0) NOT NULL PRIMARY KEY,
  CHUONGTRINHID NUMBER(24,0) NOT NULL REFERENCES DM_CHUONG_TRINH(CHUONGTRINHID),
  CHINHANHID NUMBER(24,0) NOT NULL REFERENCES VMS_CHINHANH(CHINHANHID),
  BRANCHID NUMBER(24,0) NOT NULL,
  CREATEDDATE TIMESTAMP NOT NULL,
  MODIFIEDDATE TIMESTAMP,
  CREATEDBYUSERID NUMBER(24,0) NOT NULL REFERENCES VMS_USER(USERID),
  CHANGEBYUSERID NUMBER(24,0) REFERENCES VMS_USER(USERID)
)tablespace "USERS";

CREATE TABLE VMS_STOCK_AGENT(
  STOCKAGENTID NUMBER(24,0) NOT NULL PRIMARY KEY,
  AGENTID NUMBER(24, 0) NOT NULL REFERENCES VMS_DEPARTMENT(DEPARTMENTID),
  TOTAL INTEGER DEFAULT 0 NOT NULL,
  CONSTRAINT "VMS_AGENT_UQ" UNIQUE (AGENTID)
)TABLESPACE "USERS";

CREATE TABLE VMS_GIF_DELIVERY_AGENT_HISTORY(
  GIFTDELIVERYAGENTHISTORYID NUMBER(24,0) NOT NULL PRIMARY KEY,
  USERID NUMBER(24,0) NOT NULL REFERENCES VMS_USER(USERID),
  GIFTID NUMBER(24,0) NOT NULL REFERENCES VMS_GIFT(GIFTID),
  QUANTITY INTEGER NOT NULL,
  DELIVERYTIME TIMESTAMP NOT NULL,
  STATUS INTEGER NOT NULL
)TABLESPACE "USERS";

CREATE TABLE VMS_GIFT_DELIVERY_THUEBAO(
  GIFTDELIVERYTHUEBAOID NUMBER(24, 0) NOT NULL PRIMARY KEY,
  NVGIAOID NUMBER(24, 0) NOT NULL REFERENCES VMS_USER(USERID),
  THUE_BAO VARCHAR2(20 BYTE) NOT NULL,
  DELIVERTIME TIMESTAMP NOT NULL
)TABLESPACE "USERS";

CREATE TABLE VMS_GIFT_DELIVERY_THUEBAO_HIS(
  GIFTDELIVERYTHUEBAOHISID NUMBER(24, 0) NOT NULL PRIMARY KEY,
  GIFTDELIVERYTHUEBAOID NUMBER(24, 0) NOT NULL REFERENCES VMS_GIFT_DELIVERY_THUEBAO(GIFTDELIVERYTHUEBAOID),
  MA_PHIEU VARCHAR2(20 BYTE) NOT NULL,
  GIFTID NUMBER(24, 0) NOT NULL REFERENCES VMS_GIFT(GIFTID),
  QUANTITY INTEGER NOT NULL,
  CREATEDTIME TIMESTAMP NOT NULL
)TABLESPACE "USERS";

CREATE TABLE VMS_SHOPCODE_CHINHANH(
  SHOPCODECNID NUMBER(24,0) NOT NULL PRIMARY KEY,
  SHOPCODE VARCHAR2(20) NOT NULL,
  CHINHANH INTEGER NOT NULL
)TABLESPACE "USERS";

DELETE FROM VMS_SHOPCODE_CHINHANH;
ALTER TABLE VMS_SHOPCODE_CHINHANH ADD CHINHANHID NUMBER(24,0) NOT NULL REFERENCES VMS_CHINHANH(CHINHANHID);
ALTER TABLE VMS_SHOPCODE_CHINHANH DROP COLUMN CHINHANH;

CREATE TABLE VMS_MONEY_EXCHANGE_BRANCH(
  MONEYEXCHANGEBRANCHID NUMBER(24, 0) NOT NULL PRIMARY KEY,
  EXCHANGEUSERID NUMBER(24,0) NOT NULL REFERENCES VMS_USER(USERID),
  DEALER_ID NUMBER(24,0) NOT NULL,
  DEALER_CODE VARCHAR2(20) NOT NULL,
  DEALER_NAME VARCHAR2(200) NOT NULL,
  CREATEDDATE TIMESTAMP NOT NULL
) TABLESPACE "USERS";

CREATE TABLE VMS_MONEY_EXCHANGE_BRANCH_HIS(
  MONEYEXCHANGEBRANCHHISID NUMBER(24,0) NOT NULL PRIMARY KEY,
  MONEYEXCHANGEBRANCHID NUMBER(24,0) NOT NULL REFERENCES VMS_MONEY_EXCHANGE_BRANCH(MONEYEXCHANGEBRANCHID),
  ITEMID NUMBER(24,0) NOT NULL,
  CYCLE INTEGER NOT NULL,
  EXCHANGEAMOUNT FLOAT NOT NULL,
  CREATEDDATE TIMESTAMP NOT NULL,
  CONSTRAINT "MONEYEXCHBRAID_ITEM_CYCLE_UQ" UNIQUE(MONEYEXCHANGEBRANCHID, ITEMID, CYCLE)
) TABLESPACE "USERS";

CREATE TABLE ACTION_LOG(
  LOGID NUMBER(24,0) PRIMARY KEY NOT NULL,
  CHUONGTRINHID NUMBER(24,0) NOT NULL REFERENCES DM_CHUONG_TRINH(CHUONGTRINHID),
  TABLE_LOG varchar(50) NOT NULL,
  COLUMN_ID_LOG_NAME VARCHAR(100) NOT NULL,
  USERID NUMBER(24,0) NOT NULL REFERENCES VMS_USER(USERID),
  CREATEDTIME TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR2(200)
)tablespace "USERS";

ALTER TABLE ACTION_LOG ADD COLUMN_ID_LOG_VALUE NUMBER(24,0) NOT NULL;
ALTER TABLE ACTION_LOG ADD SUPPORT_DATA VARCHAR(500);

ALTER TABLE VMS_CHINHANH ADD BRANCHID NUMBER(24, 0);

ALTER TABLE VMS_USER_PASSWORD ADD PASSWORD_TYPE NUMBER(10, 0);

ALTER TABLE VMS_USER ADD CHINHANHID NUMBER(10, 0);

CREATE SEQUENCE ACTION_LOG_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  VMS_MONEY_EXCHANGE_BRANCH_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  VMS_MONEY_EXCHANGE_BRA_HIS_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE VMS_GIFT_AGENT_TRANSFER_HIS(
  GIFTAGENTTRANSFERHISID NUMBER(24, 0) NOT NULL PRIMARY KEY,
  STOCKAGENTID NUMBER(24,0) NOT NULL REFERENCES VMS_STOCK_AGENT(STOCKAGENTID),
  QUANTITY INTEGER NOT NULL,
  NGUOICHUYENID NUMBER(24,0) NOT NULL REFERENCES VMS_USER(USERID),
  INVENTORYTOTAL INTEGER NOT NULL,
  CREATEDDATE TIMESTAMP NOT NULL
) TABLESPACE "USERS";

CREATE SEQUENCE  VMS_GIFT_AGENT_TRANS_HIS_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

ALTER TABLE VMS_MONEY_EXCHANGE_BRANCH_HIS DROP CONSTRAINT MONEYEXCHBRAID_ITEM_CYCLE_UQ;
ALTER TABLE VMS_MONEY_EXCHANGE_BRANCH_HIS ADD CONSTRAINT "MONEYEXCHBRAID_CYCLE_UQ" UNIQUE(MONEYEXCHANGEBRANCHID, CYCLE);
ALTER TABLE VMS_MONEY_EXCHANGE_BRANCH_HIS DROP COLUMN ITEMID;


insert into Vms_shopcode_chinhanh values (1, '2HCM08803', 6);
insert into Vms_shopcode_chinhanh values (2, '2HCM09473', 2);
insert into Vms_shopcode_chinhanh values (3, '2HCM00740', 1);
insert into Vms_shopcode_chinhanh values (4, '2HCM00543', 3);
insert into Vms_shopcode_chinhanh values (5, '2HCM00495', 1);
insert into Vms_shopcode_chinhanh values (6, '2HCM00551', 6);
insert into Vms_shopcode_chinhanh values (7, '2HCM00749', 1);
insert into Vms_shopcode_chinhanh values (8, '2HCM00746', 6);
insert into Vms_shopcode_chinhanh values (9, '2HCM00485', 1);
insert into Vms_shopcode_chinhanh values (10, '2HCM09746', 5);
insert into Vms_shopcode_chinhanh values (11, '2HCM09744', 4);
insert into Vms_shopcode_chinhanh values (12, '2HCM09745', 3);
insert into Vms_shopcode_chinhanh values (13, '2HCM09775', 2);
insert into Vms_shopcode_chinhanh values (14, '2HCM09806', 5);
insert into Vms_shopcode_chinhanh values (15, '2HCM09832', 4);
insert into Vms_shopcode_chinhanh values (16, '2HCM09839', 4);
insert into Vms_shopcode_chinhanh values (17, '2HCM30035', 3);
insert into Vms_shopcode_chinhanh values (18, '2HCM10008', 1);
insert into Vms_shopcode_chinhanh values (19, '2HCM10010', 1);

INSERT INTO VMS_GIFT VALUES(1, 'PMH', 'Phiếu Mua Hàng', CURRENT_TIMESTAMP, NULL);

CREATE SEQUENCE  VMS_SHOPCODE_CHINHANH_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

ALTER TABLE VMS_GIFT_DELIVERY_THUEBAO_HIS ADD CONSTRAINT "MAPHIEU_UQ" UNIQUE (MA_PHIEU);

ALTER TABLE VMS_GIF_DELIVERY_AGENT_HISTORY ADD TENNGUOIGIAOHANG VARCHAR2(150 CHAR) NOT NULL;
ALTER TABLE VMS_GIF_DELIVERY_AGENT_HISTORY ADD STOCKAGENTID NUMBER(24,0) NOT NULL REFERENCES VMS_STOCK_AGENT(STOCKAGENTID);
ALTER TABLE VMS_GIF_DELIVERY_AGENT_HISTORY ADD INVENTORYTOTAL INTEGER NOT NULL;

CREATE SEQUENCE  VMS_CHINHANH_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  VMS_GIFT_DELIVERY_THUEBAO_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  VMS_GIFT_DEL_THUEBAO_HIS_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  VMS_STOCK_AGENT_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

ALTER TABLE DM_CHUONG_TRINH ADD DBLINK_NAME VARCHAR(100 CHAR) NOT NULL;
ALTER TABLE BRANCH_MAPPING ADD CONSTRAINT "CHUONGTRINH_CHINHANH_UQ" UNIQUE (CHUONGTRINHID, CHINHANHID);

CREATE SEQUENCE VMS_CCBM_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE VMS_DM_CT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  VMS_USERGROUP_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  VMS_DEPARTMENT_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  VMS_USER_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  VMS_USER_PASSWORD_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  VMS_ROLE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  VMS_USER_ROLE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  VMS_USERGROUP_ROLE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  VMS_GIFT_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  VMS_GIFT_AGENT_TRANSACTION_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE VMS_BM_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE VMS_GIF_DEL_AGENT_HIS_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

INSERT INTO VMS_Role(ROLEID, ROLE, NAME, DESCRIPTION, CREATEDDATE) VALUES(1, 'ADMIN', 'Quản trị hệ thống', 'Quản trị hệ thống', CURRENT_DATE);
INSERT INTO VMS_Role(ROLEID, ROLE, NAME, DESCRIPTION, CREATEDDATE) VALUES(2, 'AGENT', 'Điểm giao dịch', 'Điểm giao dịch', CURRENT_DATE);

INSERT INTO VMS_USERGROUP(USERGROUPID, CODE, NAME, DESCRIPTION, CREATEDDATE) VALUES(1, 'ADMIN', 'Administrator', 'Quan tri he thong', CURRENT_DATE);
INSERT INTO VMS_USERGROUP(USERGROUPID, CODE, NAME, DESCRIPTION, CREATEDDATE) VALUES(2, 'THUEBAO', 'Thue bao', 'Thue bao', CURRENT_DATE);
INSERT INTO VMS_USERGROUP(USERGROUPID, CODE, NAME, DESCRIPTION, CREATEDDATE) VALUES(3, 'NHANVIEN', 'Nhan vien', 'Nhan vien', CURRENT_DATE);

COMMIT;