INSERT INTO MOBI_DATA_PERMISSION(PERMISSIONID, CODE, DESCRIPTION) VALUES(1, 'USER_MANAGER', 'Quản lý User');
INSERT INTO MOBI_DATA_PERMISSION(PERMISSIONID, CODE, DESCRIPTION) VALUES(2, 'USER_GROUP_MANAGER', 'Quản lý nhóm người dùng (truy cập theo nhóm)');
INSERT INTO MOBI_DATA_PERMISSION(PERMISSIONID, CODE, DESCRIPTION) VALUES(3, 'KHDN_MANAGER', 'Quản lý danh sách KHDN');
INSERT INTO MOBI_DATA_PERMISSION(PERMISSIONID, CODE, DESCRIPTION) VALUES(4, 'PACKAGE_DATA_MANAGER', 'Quản lý danh sách Gói (Mệnh giá)');
INSERT INTO MOBI_DATA_PERMISSION(PERMISSIONID, CODE, DESCRIPTION) VALUES(5, 'GENERATE_CARD_CODE_MANAGER', 'Quản lý Card Code');
INSERT INTO MOBI_DATA_PERMISSION(PERMISSIONID, CODE, DESCRIPTION) VALUES(6, 'EXPENSE_MANAGER', 'Quản lý chi phí');
INSERT INTO MOBI_DATA_PERMISSION(PERMISSIONID, CODE, DESCRIPTION) VALUES(7, 'ORDER_MANAGER', 'Quản lý đơn hàng');
INSERT INTO MOBI_DATA_PERMISSION(PERMISSIONID, CODE, DESCRIPTION) VALUES(8, 'REPORT_MANAGER', 'Xem báo cáo');

INSERT INTO MOBI_DATA_USERGROUP(USERGROUPID, CODE, DESCRIPTION) VALUES(1, 'ADMIN', 'Quản trị hệ thống');
INSERT INTO MOBI_DATA_USERGROUP(USERGROUPID, CODE, DESCRIPTION) VALUES(2, 'KHDN', 'KHDN');
INSERT INTO MOBI_DATA_USERGROUP(USERGROUPID, CODE, DESCRIPTION) VALUES(3, 'VMS_USER', 'VMS User');

INSERT INTO MOBI_DATA_USER VALUES(1, 'admin', 'cEKQ5FbL+Ng=', 'Admin', 1, 1, CURRENT_TIMESTAMP, null, null, 0, null);

INSERT INTO MOBI_DATA_PACKAGE_DATA VALUES(1, 'DataQT1B', '1000', '100MB', '01 ngày', 1, 0, 'DATA5', null);
INSERT INTO MOBI_DATA_PACKAGE_DATA VALUES(2, 'DataQT3B', '3000', '300MB', '01 ngày', 1, 0, 'DATA5', null);
INSERT INTO MOBI_DATA_PACKAGE_DATA VALUES(3, 'DataQT5B', '5000', '500MB', '01 ngày', 1, 0, 'DATA5', null);
INSERT INTO MOBI_DATA_PACKAGE_DATA VALUES(4, 'DataQT8B', '8000', '600MB', '03 ngày', 3, 0, 'DATA5', null);
INSERT INTO MOBI_DATA_PACKAGE_DATA VALUES(5, 'DataQT10B', '10000', '1000MB', '10 ngày', 10, 0, 'DATA5', null);
INSERT INTO MOBI_DATA_PACKAGE_DATA VALUES(6, 'DataQT50B', '50000', '1500MB', '31 ngày', 31, 0, 'DATA5', null);
INSERT INTO MOBI_DATA_PACKAGE_DATA VALUES(7, 'DataQT70B', '70000', '2000MB', '31 ngày', 31, 0, 'DATA5', null);
INSERT INTO MOBI_DATA_PACKAGE_DATA VALUES(8, 'DataQT35B(*)', '35000', '1.536MB truy cập IP ngoài Facebook{delimiter_line}Miễn phí truy cập IP Facebook', '31 ngày', 31, 11, 'DATA5', null);

commit;
