INSERT INTO MOBI_DATA_ROLE(ROLEID, CODE, NAME, DESCRIPTION) VALUES(1, 'ADMIN', 'Quản trị hệ thống', 'Quản trị hệ thống');
INSERT INTO MOBI_DATA_Role(ROLEID, CODE, NAME, DESCRIPTION) VALUES(2, 'KHDN', 'KHDN', 'KHDN');

INSERT INTO MOBI_DATA_USERGROUP(USERGROUPID, CODE, NAME, DESCRIPTION) VALUES(1, 'ADMIN', 'Administrator', 'Quản trị hệ thống');
INSERT INTO MOBI_DATA_USERGROUP(USERGROUPID, CODE, NAME, DESCRIPTION) VALUES(2, 'KHDN', 'KHDN', 'KHDN');
