CREATE TABLE MOBI_DATA_USERGROUP
(
   UserGroupID            NUMBER(24,0)                        NOT NULL PRIMARY KEY,
   Code                   VARCHAR(50)                   NOT NULL,
   Name                   VARCHAR(50)                  NOT NULL,
   Description            VARCHAR2(250 CHAR)                   	NULL,
  CONSTRAINT "MOBI_DATA_USERGROUP_UQ" UNIQUE (Code)
) TABLESPACE "USERS";

CREATE TABLE MOBI_DATA_ROLE
(
   RoleID                 NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   Code                   VARCHAR(50)                   NOT NULL,
   Name                   VARCHAR(150)                  NOT NULL,
   Description            VARCHAR2(250 CHAR)                   NULL,
  CONSTRAINT "MOBI_DATA_ROLE_UQ" UNIQUE (Code)
) TABLESPACE "USERS";

CREATE TABLE MOBI_DATA_USER
(
   UserId                 NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   Username               VARCHAR(100)                  NOT NULL,
   Password               VARCHAR(50)                  NULL,
   DisplayName            VARCHAR2(250 CHAR)                  NOT NULL,
   Status                 NUMBER(24,0)                            NULL,
   UserGroupID            NUMBER(24,0)                            NOT NULL,
   CreatedDate            TIMESTAMP                      NOT NULL,
   LastModified           TIMESTAMP,
   LastLogin              TIMESTAMP,

   CONSTRAINT "MOBI_DATA_USER_USERNAME_UQ" UNIQUE (Username),
   CONSTRAINT "MOBI_DATA_USER_USERGROUP_FK" FOREIGN KEY(UserGroupID) REFERENCES MOBI_DATA_USERGROUP(UserGroupID)
) TABLESPACE "USERS";

CREATE TABLE MOBI_DATA_USERGROUP_ROLE (
   UserGroupRoleID             NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   UserGroupID                 NUMBER(24,0)                            NOT NULL,
   RoleID                 NUMBER(24,0)                            NOT NULL,
   CONSTRAINT "MOBI_DATA_UGROLE_UQ" UNIQUE (UserGroupID, RoleID),
   CONSTRAINT "MOBI_DATA_UGROLE_USER_FK" FOREIGN KEY(UserGroupID) REFERENCES MOBI_DATA_USERGROUP(UserGroupID),
   CONSTRAINT "MOBI_DATA_UGROLE_ROLE_FK" FOREIGN KEY(RoleID) REFERENCES MOBI_DATA_ROLE(RoleID)
) TABLESPACE "USERS";

CREATE TABLE MOBI_DATA_USER_ROLE (
   UserRoleID             NUMBER(24,0)                            NOT NULL PRIMARY KEY,
   UserID                 NUMBER(24,0)                            NOT NULL,
   RoleID                 NUMBER(24,0)                            NOT NULL,
   CONSTRAINT "MOBI_DATA_USER_ROLE_UQ" UNIQUE (UserID, RoleID),
   CONSTRAINT "MOBI_DATA_USER_ROLE_USER_FK" FOREIGN KEY(UserID) REFERENCES MOBI_DATA_USER(UserID),
   CONSTRAINT "MOBI_DATA_USER_ROLE_ROLE_FK" FOREIGN KEY(RoleID) REFERENCES MOBI_DATA_ROLE(RoleID)
) TABLESPACE "USERS";

CREATE SEQUENCE  MOBI_DATA_USERGROUP_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  MOBI_DATA_ROLE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  MOBI_DATA_USER_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  MOBI_DATA_USERGROUP_ROLE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  MOBI_DATA_USER_ROLE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


