CREATE TABLE MOBI_DATA_PERMISSION
(
   PermissionID           NUMBER(24,0)                  NOT NULL PRIMARY KEY,
   Code                   VARCHAR(50)                   NOT NULL,
   Description            VARCHAR2(250 CHAR)            NULL,
   Permission_Type_Value  INTEGER                       NOT NULL,
   OrderNo                INTEGER                       NOT NULL,
   CONSTRAINT "MOBI_DATA_PERMISSION_UQ" UNIQUE (Code),
   CONSTRAINT "MOBI_DATA_OTYPE_ONO_UQ"  UNIQUE (Permission_Type_Value, OrderNo)
)  TABLESPACE "USERS";

CREATE TABLE MOBI_DATA_USERGROUP
(
   UserGroupID            NUMBER(24,0)                  NOT NULL PRIMARY KEY,
   Code                   VARCHAR(50)                   NOT NULL,
   Description            VARCHAR2(250 CHAR)            NULL,
   CONSTRAINT "MOBI_DATA_USERGROUP_UQ" UNIQUE (Code)
)  TABLESPACE "USERS";

CREATE TABLE MOBI_DATA_USERGROUPPERMISSION
(
   UserGroupPermissionID  NUMBER(24, 0) NOT NULL PRIMARY KEY,
   UserGroupID            NUMBER(24, 0) NOT NULL,
   PermissionID           NUMBER(24, 0) NOT NULL,
   CONSTRAINT "MOBI_DATA_UGP_UG_FK" FOREIGN KEY(UserGroupID) REFERENCES MOBI_DATA_USERGROUP(UserGroupId),
   CONSTRAINT "MOBI_DATA_UGP_PER_FK" FOREIGN KEY(PermissionID) REFERENCES MOBI_DATA_PERMISSION(PermissionID),
   CONSTRAINT "MOBI_DATA_UGP_PERMISSION_UQ" UNIQUE(UserGroupID, PermissionID)
)  TABLESPACE "USERS";

CREATE TABLE MOBI_DATA_USER
(
   UserId                 NUMBER(24,0)                  NOT NULL PRIMARY KEY,
   Username               VARCHAR(100)                  NOT NULL,
   Password               VARCHAR(50)                   NULL,
   DisplayName            VARCHAR2(250 CHAR)            NOT NULL,
   Status                 NUMBER(24,0)                  NULL,
   UserGroupID            NUMBER(24,0)                  NOT NULL,
   CreatedDate            TIMESTAMP                     NOT NULL,
   LastModified           TIMESTAMP,
   LastLogin              TIMESTAMP,
   IsLDAP                 INTEGER                       NOT NULL,
   CONSTRAINT "MOBI_DATA_USER_USERNAME_UQ" UNIQUE (Username),
   CONSTRAINT "MOBI_DATA_USER_USERGROUP_FK" FOREIGN KEY(UserGroupID) REFERENCES MOBI_DATA_USERGROUP(UserGroupID)
)  TABLESPACE "USERS";

CREATE SEQUENCE  MOBI_DATA_USERGROUP_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  MOBI_DATA_PERMISSION_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  MOBI_DATA_USER_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  MOBI_DATA_USERGROUPPER_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

commit;


